### ISSUE TITLE
Secure user's account

### ISSUE THREAD

**Issue by thegergo02** [thegergo02/gKreta#5]
In the program's current state, **it stores the username and the password in plain text** (?????), so the system has to store just the auth token. It's not secure too, so somehow we need to store that with encryption. I need to find a way of storing it securely.

**Comment by boapps** [comment]
Well, you can not encrypt something without a key/password. When developing for Android/iOS, the OS has a secure way of storing encryption keys securely in a keystore, but AFAIK you can not do this on PC. So I suggest you add the option to secure the data with a password, encrypt the token with the password and then every time the user opens the app, he or she would have to enter the password to decrypt the token. Of course this would be optional.

**Comment by szekelymilan** [comment]
You should use [keytar](https://www.npmjs.com/package/keytar).

**Comment by thegergo02** [comment]
Before I implement any of this, I need to refactor the whole "get data and send that to renderer" process, because it's a mess right now.

**Comment by thegergo02** [comment]
I can't build keytar for Node 69, so I can't use that right now. I will go for the password or no security option for now.

**Comment by szekelymilan** [comment]
You should consider using another Node.js version, or check some common issues: 
https://github.com/atom/node-keytar/issues/153

**Comment by thegergo02** [comment]
It's possible that my problem is this too, when I can I will look into it again.

**Comment by thegergo02** [comment]
Implemented keytar with f04e2d81b612d66488ef088b51a64df87ec0526a. Thanks @szekelymilan and @boapps!
